### ISSUE TITLE
Command 'Vyper: Compile' resulted in an error (command 'vyper.compileContract' not found)

### ISSUE THREAD

**Issue by DataBeast-IT** [tintinweb/vscode-vyper#4] opened 2020-10-14 15:58 UTC
I'm getting this error when trying to compile a vyper contract in VS Code with the tintinweb vyper extension.

**Command 'Vyper: Compile' resulted in an error (command 'vyper.compileContract' not found)**

My setup:
Python 3.8.6
Vyper 0.2.5+commit.a0c561c
VS code 1.50
Windows 10

Vyper is in my user path (running windows 10) and can be called directly if I open a terminal.
I installed Vyper through pip install vyper.

[edit]
I don't use a virtual environment, as this is the only python / vyper project I'm doing on the machine
[/edit]

**Comment by DataBeast-IT** [comment] 2020-10-15 19:22
It also gives a source path error, with a leading /

![image](https://user-images.githubusercontent.com/33023023/96176092-bbbb2780-0ee0-11eb-8a6e-4b9e814746e4.png)

**Comment by tintinweb** [comment] 2020-10-16 08:34
Hey @DataBeast-IT,

thanks for reporting this issue.

I think the problem is that I am passing the `uri.path` instead of the filesystem path to the compiler. on *nix/macos this is actually the same that's why I don't see the error here. on windows it is different.

I believe this should be fairly easy to fix. Would you be down to testing the release candidate before I publish it to confirm that this is fixed?

**Comment by DataBeast-IT** [comment] 2020-10-16 21:59
Sure! 

How do I do that? ;-)

**Comment by tintinweb** [comment] 2020-10-17 16:16
@DataBeast-IT here's a preview: [vscode-vyper-0 0 10 vsix](https://user-images.githubusercontent.com/2865694/96347824-80695600-10a4-11eb-8645-5bb37e47c85f.png)

* download
* rename from `png` to `.vsix` and install in vscode.

let me know if that fixes your problem.

**Comment by DataBeast-IT** [comment] 2020-10-17 22:22
I will check it on windows after the weekend, I have no access to that box at the moment.

Below is Linux! 
(should this be splitted in a windows an linux issue btw?)
Just to make sure it still works on ubuntu I tried your 0.0.10 extension on my ubuntu 20 box.

2 scenario's:
1. altering a .vy file, doing CTRL+S to save does not give a popup or error message. 
I'm not sure if it compiled at all.

2. using command palette doing Vyper:Compile gives this error
**[Compiler Exception] TypeError: Cannot read property 'toString' of undefined**


after uninstalling the 0.0.10 version, deleting it from .vscode/extensions and reinstalling 0.0.9

**Comment by DataBeast-IT** [comment] 2020-10-17 22:23
Generic question: When I compile, where does the compiled contract end up? No file is created in any directory. I checked /usr/local/bin where the vyper executable is located. Nothing to be found.

**Comment by tintinweb** [comment] 2020-10-18 15:59
> Generic question: When I compile, where does the compiled contract end up? No file is created in any directory. I checked /usr/local/bin where the vyper executable is located. Nothing to be found.

we take output artifacts from stdout. 

the vsix I shared with you [previously](https://github.com/tintinweb/vscode-vyper/issues/4#issuecomment-711037819) was broken. I've fixed a couple of issues, briefly tested it on windows, and repackaged it. Please try this one @DataBeast-IT:

[vscode-vyper-0 0 10 png -> vsix](https://user-images.githubusercontent.com/2865694/96373240-6f374c80-116b-11eb-86fc-a5ac5605d148.png)

**Comment by DataBeast-IT** [comment] 2020-10-19 19:32
On the windows box:
- saving a changed .vy gives a [compiler success] popup
- using the command palette doing Vyper:compile gives the same popup

So that is working now 👍 

Observations:
- on opening a .vy file, the extension compiles the smart contract right away and shows the popup.
- there is no output file created, debug / output windows in VScode show nothing. Within the open folder there are no new files. 

How do I find my output? I tried adding some vyper parameters. It still compiles but nothing changes.
![image](https://user-images.githubusercontent.com/33023023/96502748-1ae1aa80-1207-11eb-8b76-797db2413678.png)

**Comment by tintinweb** [comment] 2020-10-20 11:09
we currently dont save these artifacts. the compile step is basically used to detect if there are any compile-time issues with your code.

happy to implement that though, shouldn't be a lot of work.

**Comment by DataBeast-IT** [comment] 2020-10-20 15:09
Ah ok! That makes sense!

Thanks for your help!

**Comment by tintinweb** [comment] 2020-10-21 08:01
fixed in #5 

feel free to open a new issue if you want the extension to actually output bytecode somehow.

cheers and thanks for testing!

**Closed** 2020-10-21 08:02 UTC
Labels: bug
